#===================================================================
# 기본 설정 (공통)
#===================================================================
spring:
  profiles:
    active: local

application:
  name: welper-back

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000   # 1시간
  refresh-expiration: 604800000  # 7일

springdoc:
  swagger-ui:
    path: /swagger   # Swagger 단축 경로 설정
ai:
  assessment:
    base-url: http://localhost:9001   # 실제 AI 서버 주소/포트 설정하기

---
# ==================================================================
# local (개발용)
# ==================================================================
spring:
  config:
    activate:
      on-profile: local

  application:
    name: welper-back

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  datasource:
    url: "jdbc:postgresql://localhost:5432/welper_db"
    username: "welper"
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # 멀티 폼데이터를 처리하기 위해 하는 것
  # 스프링 부트 3.x 버전부터 자동 enable이 아니라 따로 설정해줘야함
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

---
# ==================================================================
# prod (운영용)
# ==================================================================
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false

springdoc:
  swagger-ui:
    path: /swagger
